export const cosmicBakeryContent = {
  metadata: {
    id: '@idle-engine/cosmic-bakery',
    title: { default: 'Cosmic Bakery', variants: {} },
    summary: { default: 'A whimsical idle game about cosmic baking', variants: {} },
    version: '0.1.0',
    engine: '>=0.4.0 <1.0.0',
    authors: ['Idle Engine Team'],
    defaultLocale: 'en-US',
    supportedLocales: ['en-US'],
    tags: ['game', 'cosmic', 'bakery'],
    links: [],
  },
  resources: [],
  generators: [],
  upgrades: [],
  achievements: [],
  automations: [],
  prestigeLayers: [],
  metrics: [],
  transforms: [],
  guildPerks: [],
  runtimeEvents: [],
};
