version: '3.9'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    command: start-dev --http-port=8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8080:8080'
  social-service:
    build:
      context: ./services/social
      dockerfile: Dockerfile
    depends_on:
      - keycloak
    environment:
      PORT: 4000
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/idle
      KEYCLOAK_AUDIENCE: idle-engine-social
    ports:
      - '4000:4000'
    command: node dist/index.js
