/* @generated */
// This file was auto-generated by tools/scripts/generate-version.mjs
// Do not edit this file directly.
//
// RUNTIME_VERSION is synchronized with packages/core/package.json version.
// To update PERSISTENCE_SCHEMA_VERSION, edit this file and run the generator.

/**
 * Runtime version constants
 *
 * These constants are used for serialization boundaries, persistence schemas,
 * and compatibility checks across the Idle Engine runtime.
 */

/**
 * Runtime semantic version.
 *
 * Corresponds to the @idle-engine/core package version. Used for:
 * - Session snapshot compatibility validation
 * - Runtime migration detection
 * - Telemetry and diagnostics correlation
 *
 * AUTO-GENERATED: This value is synchronized with packages/core/package.json.
 * Do not edit manually - run `pnpm generate:version` to regenerate.
 */
export const RUNTIME_VERSION = '0.5.0';

/**
 * Persistence schema version for session snapshots.
 *
 * Increment when the structure of session snapshot payloads changes in a
 * backwards-incompatible way. Used for:
 * - Triggering migration logic when restoring old saves
 * - Validating snapshot payload structure
 * - Coordinating with SessionPersistenceAdapter implementations
 *
 * MANUALLY MANAGED: Update this constant in version.ts before running the generator.
 * The generator preserves this value across regenerations.
 *
 * Current schema (v1):
 * - persistenceSchemaVersion: 1
 * - slotId: string
 * - capturedAt: ISO timestamp
 * - workerStep: number
 * - monotonicMs: number
 * - state: SerializedResourceState
 * - runtimeVersion: string
 * - contentDigest: ResourceDefinitionDigest
 * - flags?: { pendingMigration?, abortedRestore? }
 */
export const PERSISTENCE_SCHEMA_VERSION = 1;
