/* @generated */
// This file was auto-generated by pnpm generate.
// Do not edit this file directly.
import type { EventChannelConfiguration } from './event-bus.js';
import type { RuntimeEventManifestEntry, RuntimeEventManifestHash, RuntimeEventType } from './runtime-event.js';

export interface ContentEventDefinition {
  readonly packSlug: string;
  readonly type: RuntimeEventType;
  readonly version: number;
  readonly schema?: string;
}

export interface GeneratedRuntimeEventDefinition {
  readonly channel: number;
  readonly type: RuntimeEventType;
  readonly version: number;
  readonly packSlug: string;
  readonly schema?: string;
}

export const CONTENT_EVENT_DEFINITIONS = [
  {
    packSlug: '@idle-engine/sample-pack',
    type: 'sample:reactor-primed' as RuntimeEventType,
    version: 2,
    schema: 'packages/content-sample/content/events/sample-reactor-primed.schema.json',
  },
] as const satisfies readonly ContentEventDefinition[];

export const CONTENT_EVENT_CHANNELS: ReadonlyArray<EventChannelConfiguration> = [
  {
    definition: {
      type: 'sample:reactor-primed' as RuntimeEventType,
      version: 2,
    },
  },
];

export const GENERATED_RUNTIME_EVENT_DEFINITIONS = [
  {
    channel: 0,
    type: 'resource:threshold-reached' as RuntimeEventType,
    version: 1,
    packSlug: '@idle-engine/core',
  },
  {
    channel: 1,
    type: 'automation:toggled' as RuntimeEventType,
    version: 1,
    packSlug: '@idle-engine/core',
  },
  {
    channel: 2,
    type: 'automation:fired' as RuntimeEventType,
    version: 1,
    packSlug: '@idle-engine/core',
  },
  {
    channel: 3,
    type: 'sample:reactor-primed' as RuntimeEventType,
    version: 2,
    packSlug: '@idle-engine/sample-pack',
    schema: 'packages/content-sample/content/events/sample-reactor-primed.schema.json',
  },
] as const satisfies readonly GeneratedRuntimeEventDefinition[];

export const GENERATED_RUNTIME_EVENT_MANIFEST = {
  entries: [
    {
      channel: 0,
      type: 'resource:threshold-reached' as RuntimeEventType,
      version: 1,
    },
    {
      channel: 1,
      type: 'automation:toggled' as RuntimeEventType,
      version: 1,
    },
    {
      channel: 2,
      type: 'automation:fired' as RuntimeEventType,
      version: 1,
    },
    {
      channel: 3,
      type: 'sample:reactor-primed' as RuntimeEventType,
      version: 2,
    },
  ] as const satisfies readonly RuntimeEventManifestEntry[],
  hash: '3c3a64da' as RuntimeEventManifestHash,
} as const;

export type ContentRuntimeEventType =
  'sample:reactor-primed';

declare module './runtime-event.js' {
  interface RuntimeEventPayloadMap {
    'sample:reactor-primed': unknown;
  }
}
