name: Enforce Issue Closures

on:
  issues:
    types:
      - closed

jobs:
  require-pr:
    name: Ensure issue closed via PR
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
    steps:
      - name: Validate closing PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            if (issue.pull_request) {
              // Ignore pull requests closing themselves.
              return;
            }

            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const events = await github.paginate(
              github.rest.issues.listEventsForTimeline,
              {
                owner,
                repo,
                issue_number: issue.number,
                per_page: 100,
                mediaType: {
                  previews: ['mockingbird']
                }
              }
            );

            const mergedPulls = events.filter((event) => {
              if (event.event !== 'cross-referenced') {
                return false;
              }
              const sourceIssue = event.source?.issue;
              const prData = sourceIssue?.pull_request;
              if (!sourceIssue || !prData) {
                return false;
              }
              return sourceIssue.state === 'closed' && Boolean(prData.merged_at);
            });

            if (mergedPulls.length === 0) {
              core.info(`No merged PR found for issue #${issue.number}; reopening.`);
              await github.rest.issues.update({
                owner,
                repo,
                issue_number: issue.number,
                state: 'open'
              });

              const commentBody = [
                "🔄 Reopening: every issue should be closed via a merged pull request.",
                "",
                "Please link a PR using a closing keyword (e.g., `Fixes #${issue.number}`) so the issue can be auto-closed."
              ].join('\n');

              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: issue.number,
                body: commentBody
              });

              core.setFailed('Issue closed without a merged PR reference.');
            }
